name: yoink
description: Just Yoink It!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  adaptive_theme: ^3.6.0
  get: ^4.6.6
  settings_ui: ^2.0.2
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.3
  flutter_advanced_drawer: ^1.3.7
  youtube_parser: ^2.1.4
  youtube_explode_dart: ^2.3.5
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  toastification: ^2.3.0
  file_picker: ^8.1.4
  intl: ^0.19.0
  archive: ^3.6.1
  http: ^1.2.2
  ffmpeg_kit_flutter: ^6.0.3
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # Assets
  assets:

    # Anim
    - assets/anim/

    # Images
    - assets/img/